language: node_js
node_js: stable
cache:
  directories: 
    - node_modules
deploy:
  provider: pages
  cleanup: true
  github_token: $github_token
  local_dir: build
  target_branch: master
  on:
    branch: staging